spring.application.name=gerenciamento_estoque

spring.jpa.database=postgresql
spring.sql.init.platform=postgres
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/db_senai_estoque
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.devtools.restart.enabled=true